//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
	public class BlockComparer : IComparer<Block>,IComparer<BasicBlock>
	{
		public int Compare(Block a, Block b){
			return a.CompareTo (b);
		}
		public int Compare(BasicBlock a, BasicBlock b){
			return a.CompareTo (b);
		}
	}

